// src/types/chat.ts

export interface AttachedFile {
  name: string;
  type: "image" | "document";
  data: string; // Base64 or text content
}

export interface Message {
  role: "user" | "assistant" | "system";
  content: string;
  images?: string[];
}

export interface BrewProject {
  id: string;
  name: string;
  description: string;
  starterPrompts: string[]; // Prompts to show as quick-start buttons
  contextFiles: AttachedFile[]; // Global PDFs/Docs injected into every chat in this brew
  createdAt: number;
}

export interface ChatSession {
  id: string;
  brewId: string | null; // Null if it's a general chat outside a project
  title: string; // Auto-generated by LLM
  hoverDescription: string; // Auto-generated 1-sentence summary
  messages: Message[];
  updatedAt: number;
}
